# Generated by Django 2.1.2 on 2018-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_sample_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'MAMEZOU', 'verbose_name_plural': 'MAMEZOU'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='naiyou',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='item',
            name='study_choice',
            field=models.IntegerField(blank=True, choices=[(1, 'WEBサイト'), (2, 'WEBアプリ'), (3, 'WEBサービス'), (4, 'ios/Androidアプリ'), (5, 'システム'), (6, 'AI関連'), (7, 'RPA'), (8, '資格')], null=True, verbose_name='choice'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_6',
            field=models.BooleanField(verbose_name='チェックリスト'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_7',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
